# Task 1: Build a Relational Schema
Model an online movie rental service. Design a normalized relational schema using pandas DataFrames for the following entities:

## Step 1: Create these tables:

customers with columns: customer_id, name, email, city, signup_date
movies with columns: movie_id, title, genre, release_year, rating (1-5 scale)
rentals with columns: rental_id, customer_id, movie_id, rental_date, return_date, price
Populate with at least 8 customers, 10 movies, and 25 rentals. Make sure some customers have multiple rentals and some movies are rented multiple times.

In [161]:
import pandas as pd

# -----------------------
# customers (8+ records)
# -----------------------
customers = pd.DataFrame(
    [
        {"customer_id": 1, "name": "Orkhan Nuriyev", "email": "orkhan.n@example.com", "city": "Baku",      "signup_date": "2025-10-02"},
        {"customer_id": 2, "name": "Aysel Mammadova","email": "aysel.m@example.com",  "city": "Ganja",     "signup_date": "2025-10-11"},
        {"customer_id": 3, "name": "Murad Aliyev",   "email": "murad.a@example.com",  "city": "Sumqayit",  "signup_date": "2025-11-01"},
        {"customer_id": 4, "name": "Nigar Hasanli",  "email": "nigar.h@example.com",  "city": "Baku",      "signup_date": "2025-11-15"},
        {"customer_id": 5, "name": "Elvin Karimov",  "email": "elvin.k@example.com",  "city": "Shaki",     "signup_date": "2025-12-03"},
        {"customer_id": 6, "name": "Leyla Rahimova", "email": "leyla.r@example.com",  "city": "Lankaran",  "signup_date": "2025-12-18"},
        {"customer_id": 7, "name": "Kamran Huseynov","email": "kamran.h@example.com", "city": "Barda",     "signup_date": "2026-01-07"},
        {"customer_id": 8, "name": "Zahra Abbasova", "email": "zahra.a@example.com",  "city": "Nakhchivan","signup_date": "2026-01-22"},
    ]
)
customers["signup_date"] = pd.to_datetime(customers["signup_date"])

# -----------------------
# movies (10+ records)
# -----------------------
movies = pd.DataFrame(
    [
        {"movie_id": 101, "title": "The Last Horizon",  "genre": "Sci-Fi",     "release_year": 2019, "rating": 4},
        {"movie_id": 102, "title": "City of Echoes",    "genre": "Drama",      "release_year": 2021, "rating": 5},
        {"movie_id": 103, "title": "Midnight Heist",    "genre": "Thriller",   "release_year": 2018, "rating": 4},
        {"movie_id": 104, "title": "Laugh Lines",       "genre": "Comedy",     "release_year": 2020, "rating": 3},
        {"movie_id": 105, "title": "Desert Storm",      "genre": "Action",     "release_year": 2017, "rating": 4},
        {"movie_id": 106, "title": "Winter Letters",    "genre": "Romance",    "release_year": 2022, "rating": 5},
        {"movie_id": 107, "title": "Hidden Truth",      "genre": "Mystery",    "release_year": 2016, "rating": 3},
        {"movie_id": 108, "title": "Deep Blue Night",   "genre": "Crime",      "release_year": 2015, "rating": 4},
        {"movie_id": 109, "title": "Ancient Paths",     "genre": "Adventure",  "release_year": 2014, "rating": 4},
        {"movie_id": 110, "title": "Neon Skies",        "genre": "Sci-Fi",     "release_year": 2023, "rating": 5},
    ]
)

# -----------------------
# rentals (25+ records)
# -----------------------
rentals = pd.DataFrame(
    [
        {"rental_id": 1001, "customer_id": 1, "movie_id": 101, "rental_date": "2026-02-01", "return_date": "2026-02-03", "price": 3.99},
        {"rental_id": 1002, "customer_id": 1, "movie_id": 103, "rental_date": "2026-02-05", "return_date": "2026-02-07", "price": 4.49},
        {"rental_id": 1003, "customer_id": 1, "movie_id": 110, "rental_date": "2026-02-12", "return_date": "2026-02-13", "price": 5.49},

        {"rental_id": 1004, "customer_id": 2, "movie_id": 102, "rental_date": "2026-02-02", "return_date": "2026-02-04", "price": 4.99},
        {"rental_id": 1005, "customer_id": 2, "movie_id": 104, "rental_date": "2026-02-10", "return_date": "2026-02-11", "price": 2.99},
        {"rental_id": 1006, "customer_id": 2, "movie_id": 105, "rental_date": "2026-02-18", "return_date": "2026-02-20", "price": 3.99},

        {"rental_id": 1007, "customer_id": 3, "movie_id": 103, "rental_date": "2026-02-03", "return_date": "2026-02-05", "price": 4.49},
        {"rental_id": 1008, "customer_id": 3, "movie_id": 108, "rental_date": "2026-02-14", "return_date": "2026-02-16", "price": 3.49},
        {"rental_id": 1009, "customer_id": 3, "movie_id": 101, "rental_date": "2026-02-22", "return_date": "2026-02-24", "price": 3.99},
        {"rental_id": 1010, "customer_id": 3, "movie_id": 106, "rental_date": "2026-02-27", "return_date": "2026-03-01", "price": 4.99},

        {"rental_id": 1011, "customer_id": 4, "movie_id": 102, "rental_date": "2026-02-06", "return_date": "2026-02-08", "price": 4.99},
        {"rental_id": 1012, "customer_id": 4, "movie_id": 107, "rental_date": "2026-02-15", "return_date": "2026-02-17", "price": 2.49},
        {"rental_id": 1013, "customer_id": 4, "movie_id": 110, "rental_date": "2026-02-23", "return_date": "2026-02-25", "price": 5.49},

        {"rental_id": 1014, "customer_id": 5, "movie_id": 105, "rental_date": "2026-02-04", "return_date": "2026-02-06", "price": 3.99},
        {"rental_id": 1015, "customer_id": 5, "movie_id": 109, "rental_date": "2026-02-09", "return_date": "2026-02-12", "price": 3.49},
        {"rental_id": 1016, "customer_id": 5, "movie_id": 103, "rental_date": "2026-02-26", "return_date": "2026-02-28", "price": 4.49},

        {"rental_id": 1017, "customer_id": 6, "movie_id": 106, "rental_date": "2026-02-07", "return_date": "2026-02-09", "price": 4.99},
        {"rental_id": 1018, "customer_id": 6, "movie_id": 104, "rental_date": "2026-02-19", "return_date": "2026-02-20", "price": 2.99},
        {"rental_id": 1019, "customer_id": 6, "movie_id": 108, "rental_date": "2026-02-24", "return_date": "2026-02-26", "price": 3.49},

        {"rental_id": 1020, "customer_id": 7, "movie_id": 101, "rental_date": "2026-02-08", "return_date": "2026-02-10", "price": 3.99},
        {"rental_id": 1021, "customer_id": 7, "movie_id": 102, "rental_date": "2026-02-13", "return_date": "2026-02-15", "price": 4.99},
        {"rental_id": 1022, "customer_id": 7, "movie_id": 105, "rental_date": "2026-02-21", "return_date": "2026-02-23", "price": 3.99},
        {"rental_id": 1023, "customer_id": 7, "movie_id": 110, "rental_date": "2026-02-28", "return_date": "2026-03-02", "price": 5.49},

        {"rental_id": 1024, "customer_id": 8, "movie_id": 109, "rental_date": "2026-02-11", "return_date": "2026-02-14", "price": 3.49},
        {"rental_id": 1025, "customer_id": 8, "movie_id": 103, "rental_date": "2026-02-16", "return_date": "2026-02-18", "price": 4.49},
    ]
)

rentals["rental_date"] = pd.to_datetime(rentals["rental_date"])
rentals["return_date"] = pd.to_datetime(rentals["return_date"])

# Quick sanity checks (optional)
print(customers.shape, movies.shape, rentals.shape)
print("Customers with multiple rentals:\n", rentals["customer_id"].value_counts().head())
print("Movies rented multiple times:\n", rentals["movie_id"].value_counts().head())

customers.head(), movies.head(), rentals.head()

(8, 5) (10, 5) (25, 6)
Customers with multiple rentals:
 customer_id
3    4
7    4
1    3
2    3
4    3
Name: count, dtype: int64
Movies rented multiple times:
 movie_id
103    4
101    3
110    3
102    3
105    3
Name: count, dtype: int64

(   customer_id             name                 email      city signup_date
 0            1   Orkhan Nuriyev  orkhan.n@example.com      Baku  2025-10-02
 1            2  Aysel Mammadova   aysel.m@example.com     Ganja  2025-10-11
 2            3     Murad Aliyev   murad.a@example.com  Sumqayit  2025-11-01
 3            4    Nigar Hasanli   nigar.h@example.com      Baku  2025-11-15
 4            5    Elvin Karimov   elvin.k@example.com     Shaki  2025-12-03,
    movie_id             title     genre  release_year  rating
 0       101  The Last Horizon    Sci-Fi          2019       4
 1       102    City of Echoes     Drama          2021       5
 2       103    Midnight Heist  Thriller          2018       4
 3       104       Laugh Lines    Comedy          2020       3
 4       105      Desert Storm    Action          2017       4,
    rental_id  customer_id  movie_id rental_date return_date  price
 0       1001            1       101  2026-02-01  2026-02-03   3.99
 1       1002            1       103  2026-02-05  2026-02-07   4.49
 2       1003            1       110  2026-02-12  2026-02-13   5.49
 3       1004            2       102  2026-02-02  2026-02-04   4.99
 4       1005            2       104  2026-02-10  2026-02-11   2.99)

## Step 2: Write and execute these queries using pandas operations:

Find all movies rented by a specific customer (requires joining rentals with movies).
Find the top 5 most-rented movies (group and count).
Compute the total revenue per genre (join rentals with movies, group by genre, sum price).
Find customers who have never rented a movie rated below 3 (multi-step filtering).

In [162]:
customers

   customer_id             name                 email        city signup_date
0            1   Orkhan Nuriyev  orkhan.n@example.com        Baku  2025-10-02
1            2  Aysel Mammadova   aysel.m@example.com       Ganja  2025-10-11
2            3     Murad Aliyev   murad.a@example.com    Sumqayit  2025-11-01
3            4    Nigar Hasanli   nigar.h@example.com        Baku  2025-11-15
4            5    Elvin Karimov   elvin.k@example.com       Shaki  2025-12-03
5            6   Leyla Rahimova   leyla.r@example.com    Lankaran  2025-12-18
6            7  Kamran Huseynov  kamran.h@example.com       Barda  2026-01-07
7            8   Zahra Abbasova   zahra.a@example.com  Nakhchivan  2026-01-22

In [163]:
movies

   movie_id             title      genre  release_year  rating
0       101  The Last Horizon     Sci-Fi          2019       4
1       102    City of Echoes      Drama          2021       5
2       103    Midnight Heist   Thriller          2018       4
3       104       Laugh Lines     Comedy          2020       3
4       105      Desert Storm     Action          2017       4
5       106    Winter Letters    Romance          2022       5
6       107      Hidden Truth    Mystery          2016       3
7       108   Deep Blue Night      Crime          2015       4
8       109     Ancient Paths  Adventure          2014       4
9       110        Neon Skies     Sci-Fi          2023       5

In [164]:
rentals

    rental_id  customer_id  movie_id rental_date return_date  price
0        1001            1       101  2026-02-01  2026-02-03   3.99
1        1002            1       103  2026-02-05  2026-02-07   4.49
2        1003            1       110  2026-02-12  2026-02-13   5.49
3        1004            2       102  2026-02-02  2026-02-04   4.99
4        1005            2       104  2026-02-10  2026-02-11   2.99
5        1006            2       105  2026-02-18  2026-02-20   3.99
6        1007            3       103  2026-02-03  2026-02-05   4.49
7        1008            3       108  2026-02-14  2026-02-16   3.49
8        1009            3       101  2026-02-22  2026-02-24   3.99
9        1010            3       106  2026-02-27  2026-03-01   4.99
10       1011            4       102  2026-02-06  2026-02-08   4.99
11       1012            4       107  2026-02-15  2026-02-17   2.49
12       1013            4       110  2026-02-23  2026-02-25   5.49
13       1014            5       105  2026-02-04  2026-02-06   3.99
14       1015            5       109  2026-02-09  2026-02-12   3.49
15       1016            5       103  2026-02-26  2026-02-28   4.49
16       1017            6       106  2026-02-07  2026-02-09   4.99
17       1018            6       104  2026-02-19  2026-02-20   2.99
18       1019            6       108  2026-02-24  2026-02-26   3.49
19       1020            7       101  2026-02-08  2026-02-10   3.99
20       1021            7       102  2026-02-13  2026-02-15   4.99
21       1022            7       105  2026-02-21  2026-02-23   3.99
22       1023            7       110  2026-02-28  2026-03-02   5.49
23       1024            8       109  2026-02-11  2026-02-14   3.49
24       1025            8       103  2026-02-16  2026-02-18   4.49

In [165]:
rentals_merged = rentals.merge( movies, on =['movie_id'], how='left')
rentals_merged

,rental_id,customer_id,movie_id,rental_date,return_date,price,title,genre,release_year,rating
0,1001,1,101,2026-02-01,2026-02-03,3.99,The Last Horizon,Sci-Fi,2019,4
1,1002,1,103,2026-02-05,2026-02-07,4.49,Midnight Heist,Thriller,2018,4
2,1003,1,110,2026-02-12,2026-02-13,5.49,Neon Skies,Sci-Fi,2023,5
3,1004,2,102,2026-02-02,2026-02-04,4.99,City of Echoes,Drama,2021,5
4,1005,2,104,2026-02-10,2026-02-11,2.99,Laugh Lines,Comedy,2020,3
5,1006,2,105,2026-02-18,2026-02-20,3.99,Desert Storm,Action,2017,4
6,1007,3,103,2026-02-03,2026-02-05,4.49,Midnight Heist,Thriller,2018,4
7,1008,3,108,2026-02-14,2026-02-16,3.49,Deep Blue Night,Crime,2015,4
8,1009,3,101,2026-02-22,2026-02-24,3.99,The Last Horizon,Sci-Fi,2019,4
9,1010,3,106,2026-02-27,2026-03-01,4.99,Winter Letters,Romance,2022,5
10,1011,4,102,2026-02-06,2026-02-08,4.99,City of Echoes,Drama,2021,5
11,1012,4,107,2026-02-15,2026-02-17,2.49,Hidden Truth,Mystery,2016,3
12,1013,4,110,2026-02-23,2026-02-25,5.49,Neon Skies,Sci-Fi,2023,5
13,1014,5,105,2026-02-04,2026-02-06,3.99,Desert Storm,Action,2017,4
14,1015,5,109,2026-02-09,2026-02-12,3.49,Ancient Paths,Adventure,2014,4
15,1016,5,103,2026-02-26,2026-02-28,4.49,Midnight Heist,Thriller,2018,4
16,1017,6,106,2026-02-07,2026-02-09,4.99,Winter Letters,Romance,2022,5
17,1018,6,104,2026-02-19,2026-02-20,2.99,Laugh Lines,Comedy,2020,3
18,1019,6,108,2026-02-24,2026-02-26,3.49,Deep Blue Night,Crime,2015,4
19,1020,7,101,2026-02-08,2026-02-10,3.99,The Last Horizon,Sci-Fi,2019,4
20,1021,7,102,2026-02-13,2026-02-15,4.99,City of Echoes,Drama,2021,5
21,1022,7,105,2026-02-21,2026-02-23,3.99,Desert Storm,Action,2017,4
22,1023,7,110,2026-02-28,2026-03-02,5.49,Neon Skies,Sci-Fi,2023,5
23,1024,8,109,2026-02-11,2026-02-14,3.49,Ancient Paths,Adventure,2014,4
24,1025,8,103,2026-02-16,2026-02-18,4.49,Midnight Heist,Thriller,2018,4

**Find all movies rented by a specific customer (requires joining rentals with movies).**

In [166]:
rentals_merged.loc[rentals_merged['customer_id']== 1, ["customer_id","rental_id", "rental_date", "return_date",
              "movie_id", "title", "genre", "rating", "price"]]

,customer_id,rental_id,rental_date,return_date,movie_id,title,genre,rating,price
0,1,1001,2026-02-01,2026-02-03,101,The Last Horizon,Sci-Fi,4,3.99
1,1,1002,2026-02-05,2026-02-07,103,Midnight Heist,Thriller,4,4.49
2,1,1003,2026-02-12,2026-02-13,110,Neon Skies,Sci-Fi,5,5.49

**Find the top 5 most-rented movies (group and count).**

In [167]:
top5 = (
    rentals.groupby("movie_id")
           .size()
           .sort_values(ascending=False)
           .head(5)
           .reset_index(name="rental_count")
           .merge(movies[["movie_id", "title"]], on="movie_id")
)

top5

   movie_id  rental_count             title
0       103             4    Midnight Heist
1       101             3  The Last Horizon
2       102             3    City of Echoes
3       105             3      Desert Storm
4       110             3        Neon Skies

**Compute the total revenue per genre (join rentals with movies, group by genre, sum price).**

In [168]:
rentals_merged.groupby('genre')['price'].sum()

genre
Action       11.97
Adventure     6.98
Comedy        5.98
Crime         6.98
Drama        14.97
Mystery       2.49
Romance       9.98
Sci-Fi       28.44
Thriller     17.96
Name: price, dtype: float64

**Find customers who have never rented a movie rated below 3 (multi-step filtering).**

In [169]:
full_table = rentals_merged.merge(customers, on=['customer_id'], how='left')
full_table

,rental_id,customer_id,movie_id,rental_date,return_date,price,title,genre,release_year,rating,name,email,city,signup_date
0,1001,1,101,2026-02-01,2026-02-03,3.99,The Last Horizon,Sci-Fi,2019,4,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
1,1002,1,103,2026-02-05,2026-02-07,4.49,Midnight Heist,Thriller,2018,4,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
2,1003,1,110,2026-02-12,2026-02-13,5.49,Neon Skies,Sci-Fi,2023,5,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
3,1004,2,102,2026-02-02,2026-02-04,4.99,City of Echoes,Drama,2021,5,Aysel Mammadova,aysel.m@example.com,Ganja,2025-10-11
4,1005,2,104,2026-02-10,2026-02-11,2.99,Laugh Lines,Comedy,2020,3,Aysel Mammadova,aysel.m@example.com,Ganja,2025-10-11
5,1006,2,105,2026-02-18,2026-02-20,3.99,Desert Storm,Action,2017,4,Aysel Mammadova,aysel.m@example.com,Ganja,2025-10-11
6,1007,3,103,2026-02-03,2026-02-05,4.49,Midnight Heist,Thriller,2018,4,Murad Aliyev,murad.a@example.com,Sumqayit,2025-11-01
7,1008,3,108,2026-02-14,2026-02-16,3.49,Deep Blue Night,Crime,2015,4,Murad Aliyev,murad.a@example.com,Sumqayit,2025-11-01
8,1009,3,101,2026-02-22,2026-02-24,3.99,The Last Horizon,Sci-Fi,2019,4,Murad Aliyev,murad.a@example.com,Sumqayit,2025-11-01
9,1010,3,106,2026-02-27,2026-03-01,4.99,Winter Letters,Romance,2022,5,Murad Aliyev,murad.a@example.com,Sumqayit,2025-11-01
10,1011,4,102,2026-02-06,2026-02-08,4.99,City of Echoes,Drama,2021,5,Nigar Hasanli,nigar.h@example.com,Baku,2025-11-15
11,1012,4,107,2026-02-15,2026-02-17,2.49,Hidden Truth,Mystery,2016,3,Nigar Hasanli,nigar.h@example.com,Baku,2025-11-15
12,1013,4,110,2026-02-23,2026-02-25,5.49,Neon Skies,Sci-Fi,2023,5,Nigar Hasanli,nigar.h@example.com,Baku,2025-11-15
13,1014,5,105,2026-02-04,2026-02-06,3.99,Desert Storm,Action,2017,4,Elvin Karimov,elvin.k@example.com,Shaki,2025-12-03
14,1015,5,109,2026-02-09,2026-02-12,3.49,Ancient Paths,Adventure,2014,4,Elvin Karimov,elvin.k@example.com,Shaki,2025-12-03
15,1016,5,103,2026-02-26,2026-02-28,4.49,Midnight Heist,Thriller,2018,4,Elvin Karimov,elvin.k@example.com,Shaki,2025-12-03
16,1017,6,106,2026-02-07,2026-02-09,4.99,Winter Letters,Romance,2022,5,Leyla Rahimova,leyla.r@example.com,Lankaran,2025-12-18
17,1018,6,104,2026-02-19,2026-02-20,2.99,Laugh Lines,Comedy,2020,3,Leyla Rahimova,leyla.r@example.com,Lankaran,2025-12-18
18,1019,6,108,2026-02-24,2026-02-26,3.49,Deep Blue Night,Crime,2015,4,Leyla Rahimova,leyla.r@example.com,Lankaran,2025-12-18
19,1020,7,101,2026-02-08,2026-02-10,3.99,The Last Horizon,Sci-Fi,2019,4,Kamran Huseynov,kamran.h@example.com,Barda,2026-01-07
20,1021,7,102,2026-02-13,2026-02-15,4.99,City of Echoes,Drama,2021,5,Kamran Huseynov,kamran.h@example.com,Barda,2026-01-07
21,1022,7,105,2026-02-21,2026-02-23,3.99,Desert Storm,Action,2017,4,Kamran Huseynov,kamran.h@example.com,Barda,2026-01-07
22,1023,7,110,2026-02-28,2026-03-02,5.49,Neon Skies,Sci-Fi,2023,5,Kamran Huseynov,kamran.h@example.com,Barda,2026-01-07
23,1024,8,109,2026-02-11,2026-02-14,3.49,Ancient Paths,Adventure,2014,4,Zahra Abbasova,zahra.a@example.com,Nakhchivan,2026-01-22
24,1025,8,103,2026-02-16,2026-02-18,4.49,Midnight Heist,Thriller,2018,4,Zahra Abbasova,zahra.a@example.com,Nakhchivan,2026-01-22

In [170]:
customers[
    ~customers['customer_id'].isin(
        full_table.loc[full_table['rating'] < 3, 'customer_id']
    )
]

   customer_id             name                 email        city signup_date
0            1   Orkhan Nuriyev  orkhan.n@example.com        Baku  2025-10-02
1            2  Aysel Mammadova   aysel.m@example.com       Ganja  2025-10-11
2            3     Murad Aliyev   murad.a@example.com    Sumqayit  2025-11-01
3            4    Nigar Hasanli   nigar.h@example.com        Baku  2025-11-15
4            5    Elvin Karimov   elvin.k@example.com       Shaki  2025-12-03
5            6   Leyla Rahimova   leyla.r@example.com    Lankaran  2025-12-18
6            7  Kamran Huseynov  kamran.h@example.com       Barda  2026-01-07
7            8   Zahra Abbasova   zahra.a@example.com  Nakhchivan  2026-01-22

## Step 3: Demonstrate normalization.
Show what the data would look like as a single denormalized table (join all three tables). Write a markdown cell explaining what redundancy appears and why the normalized version is preferable for updates.

In [171]:
full_table.head() # I merged all 3 tables in previous task

,rental_id,customer_id,movie_id,rental_date,return_date,price,title,genre,release_year,rating,name,email,city,signup_date
0,1001,1,101,2026-02-01,2026-02-03,3.99,The Last Horizon,Sci-Fi,2019,4,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
1,1002,1,103,2026-02-05,2026-02-07,4.49,Midnight Heist,Thriller,2018,4,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
2,1003,1,110,2026-02-12,2026-02-13,5.49,Neon Skies,Sci-Fi,2023,5,Orkhan Nuriyev,orkhan.n@example.com,Baku,2025-10-02
3,1004,2,102,2026-02-02,2026-02-04,4.99,City of Echoes,Drama,2021,5,Aysel Mammadova,aysel.m@example.com,Ganja,2025-10-11
4,1005,2,104,2026-02-10,2026-02-11,2.99,Laugh Lines,Comedy,2020,3,Aysel Mammadova,aysel.m@example.com,Ganja,2025-10-11

***Normalization demo (Denormalized vs Normalized)***

**Denormalized table (joined view):** When we join `rentals` + `customers` + `movies` into one table, each rental row repeats customer and movie attributes.

**Redundancy that appears:**
- Customer fields (`name`, `email`, `city`, `signup_date`) are duplicated for every rental that the same customer makes.
- Movie fields (`title`, `genre`, `release_year`, `rating`) are duplicated for every rental of the same movie.

**Why the normalized version is better for updates:**
- In the normalized design, customer details live only in `customers` and movie details live only in `movies`.  
  If a customer changes email or a movie’s metadata needs correction, you update **one row** in the appropriate table.
- In a denormalized table, the same information may exist in many rows, so updates require changing **many rows**, which is slower and risks inconsistencies (some rows updated, others not).
- Keeping `rentals` as a fact table with only keys (`customer_id`, `movie_id`) plus rental-specific attributes (`rental_date`, `return_date`, `price`) reduces duplication and preserves data integrity.

# Task 2: Model the Same Data as Documents
Represent the same movie rental data using the document model.

## Step 1: Create a list of customer documents (Python dictionaries)
where each document contains the customer's information and a nested list of their rental history, with movie details embedded in each rental entry.

In [172]:
customers.head()

   customer_id             name                 email      city signup_date
0            1   Orkhan Nuriyev  orkhan.n@example.com      Baku  2025-10-02
1            2  Aysel Mammadova   aysel.m@example.com     Ganja  2025-10-11
2            3     Murad Aliyev   murad.a@example.com  Sumqayit  2025-11-01
3            4    Nigar Hasanli   nigar.h@example.com      Baku  2025-11-15
4            5    Elvin Karimov   elvin.k@example.com     Shaki  2025-12-03

In [173]:
rentals.head()

   rental_id  customer_id  movie_id rental_date return_date  price
0       1001            1       101  2026-02-01  2026-02-03   3.99
1       1002            1       103  2026-02-05  2026-02-07   4.49
2       1003            1       110  2026-02-12  2026-02-13   5.49
3       1004            2       102  2026-02-02  2026-02-04   4.99
4       1005            2       104  2026-02-10  2026-02-11   2.99

In [174]:
movies.head()

   movie_id             title     genre  release_year  rating
0       101  The Last Horizon    Sci-Fi          2019       4
1       102    City of Echoes     Drama          2021       5
2       103    Midnight Heist  Thriller          2018       4
3       104       Laugh Lines    Comedy          2020       3
4       105      Desert Storm    Action          2017       4

In [175]:
# 1) rentals + movies join: hər rental-a movie detallarını embed etmək üçün
rentals_with_movies = rentals.merge(
    movies,
    on="movie_id",
    how="left",
    suffixes=("", "_movie")
)

# 2) Customer docs: hər customer üçün nested rental_history
customer_docs = []
for _, c in customers.iterrows():
    # həmin customer-a aid rental-ları seç
    r = rentals_with_movies[rentals_with_movies["customer_id"] == c["customer_id"]].copy()
    r = r.sort_values("rental_date")

    rental_history = []
    for _, row in r.iterrows():
        rental_history.append({
            "rental_id": int(row["rental_id"]),
            "rental_date": row["rental_date"],
            "return_date": row["return_date"],
            "price": float(row["price"]),
            "movie": {  # EMBEDDED movie details
                "movie_id": int(row["movie_id"]),
                "title": row["title"],
                "genre": row["genre"],
                "release_year": int(row["release_year"]),
                "rating": int(row["rating"]),
            }
        })

    customer_docs.append({
        "customer_id": int(c["customer_id"]),
        "name": c["name"],
        "email": c["email"],
        "city": c["city"],
        "signup_date": c["signup_date"],
        "rental_history": rental_history
    })

# Nəticəyə baxış (məs: 1-ci customer doc)
customer_docs[0]

{'customer_id': 1,
 'name': 'Orkhan Nuriyev',
 'email': 'orkhan.n@example.com',
 'city': 'Baku',
 'signup_date': Timestamp('2025-10-02 00:00:00'),
 'rental_history': [{'rental_id': 1001,
   'rental_date': Timestamp('2026-02-01 00:00:00'),
   'return_date': Timestamp('2026-02-03 00:00:00'),
   'price': 3.99,
   'movie': {'movie_id': 101,
    'title': 'The Last Horizon',
    'genre': 'Sci-Fi',
    'release_year': 2019,
    'rating': 4}},
  {'rental_id': 1002,
   'rental_date': Timestamp('2026-02-05 00:00:00'),
   'return_date': Timestamp('2026-02-07 00:00:00'),
   'price': 4.49,
   'movie': {'movie_id': 103,
    'title': 'Midnight Heist',
    'genre': 'Thriller',
    'release_year': 2018,
    'rating': 4}},
  {'rental_id': 1003,
   'rental_date': Timestamp('2026-02-12 00:00:00'),
   'return_date': Timestamp('2026-02-13 00:00:00'),
   'price': 5.49,
   'movie': {'movie_id': 110,
    'title': 'Neon Skies',
    'genre': 'Sci-Fi',
    'release_year': 2023,
    'rating': 5}}]}

## Step 2: Execute the same four queries from Task 1 on the document collection:

Find all movies rented by a specific customer.
Find the top 5 most-rented movies.
Compute total revenue per genre.
Find customers who have never rented a movie rated below 3

Find all movies rented by a specific customer.

In [176]:
# 1) Find all movies rented by a specific customer
customer_id = 1

movies_rented = [
    r["movie"]["title"]
    for doc in customer_docs
    if doc["customer_id"] == customer_id
    for r in doc["rental_history"]
]

movies_rented

['The Last Horizon', 'Midnight Heist', 'Neon Skies']

Find the top 5 most-rented movies.

In [177]:
# 2) Top 5 most-rented movies
from collections import Counter

movie_counts = Counter(
    r["movie"]["title"]
    for doc in customer_docs
    for r in doc["rental_history"]
)

top5_most_rented = movie_counts.most_common(5)
top5_most_rented  # list of (title, count)

[('Midnight Heist', 4),
 ('The Last Horizon', 3),
 ('Neon Skies', 3),
 ('City of Echoes', 3),
 ('Desert Storm', 3)]

Compute total revenue per genre.

In [178]:
# 3) Total revenue per genre
from collections import defaultdict

revenue_by_genre = defaultdict(float)

for doc in customer_docs:
    for r in doc["rental_history"]:
        revenue_by_genre[r["movie"]["genre"]] += float(r["price"])

dict(revenue_by_genre)

{'Sci-Fi': 28.440000000000005,
 'Thriller': 17.96,
 'Drama': 14.97,
 'Comedy': 5.98,
 'Action': 11.97,
 'Crime': 6.98,
 'Romance': 9.98,
 'Mystery': 2.49,
 'Adventure': 6.98}

Find customers who have never rented a movie rated below 3.

In [179]:
# 4) Customers who have never rented a movie rated below 3
good_customers = [
    doc["name"]
    for doc in customer_docs
    if all(r["movie"]["rating"] >= 3 for r in doc["rental_history"])
]

good_customers

['Orkhan Nuriyev',
 'Aysel Mammadova',
 'Murad Aliyev',
 'Nigar Hasanli',
 'Elvin Karimov',
 'Leyla Rahimova',
 'Kamran Huseynov',
 'Zahra Abbasova']

## Step 3: Write a markdown cell comparing the document queries to the relational queries. Which queries were easier to write? Which were harder? For which query pattern does the document model have a clear advantage?

### Comparison: Document Model vs Relational Model

In the relational model, the data is stored in separate tables (`customers`, `movies`, and `rentals`). To answer many questions, we must join these tables using operations like `merge`. This makes the structure normalized and avoids redundancy, but queries often require multiple steps.

In the document model, each customer document already contains their rental history with embedded movie information. Because related data is stored together, some queries become simpler since no joins are required.

**Easier in the document model:**
- Finding all movies rented by a specific customer was easier. The rentals are already nested inside the customer document, so we only iterate through that customer’s `rental_history`.

**Harder in the document model:**
- Queries that require aggregating data across all customers (such as finding the top 5 most-rented movies or total revenue per genre) were harder. We had to loop through all documents and rentals manually to compute counts or sums.

**Clear advantage of the document model:**
- The document model is particularly strong when accessing data that naturally belongs together, such as retrieving a customer's full rental history. This pattern benefits from having related information embedded in a single document, avoiding joins and making read operations straightforward.

# Task 3: Model Relationships as a Graph
Build a graph representation of the rental data to answer relationship-based questions.

## Step 1: Create a graph using Python dictionaries where:

Nodes represent customers, movies, and genres.
Edges represent relationships: rented (customer → movie), belongs_to (movie → genre), lives_in (customer → city).

In [180]:
nodes = {
    "c001": {"type": "customer", "name": "Alice"},
    "c002": {"type": "customer", "name": "Bob"},

    "m001": {"type": "movie", "title": "Inception"},
    "m002": {"type": "movie", "title": "Titanic"},
    "m003": {"type": "movie", "title": "Avatar"},

    "sci_fi": {"type": "genre", "name": "Sci-Fi"},
    "romance": {"type": "genre", "name": "Romance"},
    "action": {"type": "genre", "name": "Action"},

    "london": {"type": "city", "name": "London"},
    "paris": {"type": "city", "name": "Paris"}
}

In [181]:
edges = [
    ("c001", "rented", "m001"),
    ("c001", "rented", "m002"),
    ("c002", "rented", "m003"),

    ("m001", "belongs_to", "sci_fi"),
    ("m002", "belongs_to", "romance"),
    ("m003", "belongs_to", "action"),

    ("c001", "lives_in", "london"),
    ("c002", "lives_in", "paris")
]

## Step 2: Write traversal functions to answer:

"Which movies did customer X rent?" — one hop from customer through rented edges.
"Which genres does customer X prefer?" — two hops: customer → movies → genres, then count.
"Which customers share a genre preference with customer X?" — three hops: customer X → movies → genres → other customers who rented movies in the same genre.
"Recommend movies for customer X" — find movies in their preferred genres that they have not yet rented.

"Which movies did customer X rent?" — one hop from customer through rented edges

In [182]:
def movies_rented_by_customer(customer_id):
    movies = []
    
    for src, rel, dst in edges:
        if src == customer_id and rel == "rented":
            movies.append(nodes[dst]["title"])
    
    return movies

In [183]:
movies_rented_by_customer('c002')

['Avatar']

"Which genres does customer X prefer?" — two hops: customer → movies → genres, then count.

In [184]:
from collections import Counter

def preferred_genres(customer_id):
    
    genres = []
    
    for src, rel, movie in edges:
        if src == customer_id and rel == "rented":
            
            for m, r, genre in edges:
                if m == movie and r == "belongs_to":
                    genres.append(nodes[genre]["name"])
    
    return Counter(genres)

In [185]:
preferred_genres('c001')

Counter({'Sci-Fi': 1, 'Romance': 1})

"Which customers share a genre preference with customer X?" — three hops: customer X → movies → genres → other customers who rented movies in the same genre.

In [186]:
def similar_customers(customer_id):
    
    genres = set(preferred_genres(customer_id).keys())
    similar = set()
    
    for movie, rel, genre in edges:
        if rel == "belongs_to" and nodes[genre]["name"] in genres:
            
            for customer, r, m in edges:
                if r == "rented" and m == movie and customer != customer_id:
                    similar.add(nodes[customer]["name"])
    
    return list(similar)

In [187]:
similar_customers('c001')

[]

"Recommend movies for customer X" — find movies in their preferred genres that they have not yet rented.

In [188]:
def recommend_movies(customer_id):
    
    rented = set()
    
    for src, rel, movie in edges:
        if src == customer_id and rel == "rented":
            rented.add(movie)
    
    genres = set(preferred_genres(customer_id).keys())
    
    recommendations = set()
    
    for movie, rel, genre in edges:
        if rel == "belongs_to" and nodes[genre]["name"] in genres:
            if movie not in rented:
                recommendations.add(nodes[movie]["title"])
    
    return list(recommendations)

In [189]:
recommend_movies('c002')

[]

## Step 3: Write a markdown cell explaining why the recommendation query (Task 3, question 4) 
would be difficult to express in SQL or with documents. What makes the graph model natural for this kind of traversal?

### Why the recommendation query is harder in relational or document models

The recommendation query requires following multiple relationships in sequence. In this task we traverse:  
**customer → movies they rented → genres of those movies → other movies in the same genres that the customer has not rented yet.**

In a relational database, this type of query requires several **JOIN operations** between tables such as `customers`, `rentals`, and `movies`. The query becomes complex because the same tables must be joined multiple times and additional conditions are needed to exclude movies already rented. As the number of relationships grows, the SQL query becomes longer and harder to maintain.

In the document model, the rental history is embedded inside customer documents. While retrieving a single customer's rentals is easy, answering a query that requires looking across many customers or genres requires iterating through many documents and manually aggregating results. This makes cross-document relationship queries more complicated and less efficient.

The **graph model** is natural for this problem because relationships are first-class elements of the data model. Traversing from one node to another through edges (customer → movie → genre → movie) is straightforward and matches the way the recommendation logic works. Instead of performing complex joins or scanning many documents, the graph simply follows connected edges. This makes multi-step relationship queries easier to express and more intuitive to implement.

# Task 4: OLTP vs OLAP Workload Analysis
This task asks you to reason about how different database types handle different workloads.

## Step 1: Create a DataFrame representing a log of 5,000 e-commerce transactions with columns:
transaction_id, customer_id, product_id, amount, payment_method, timestamp, status (completed/refunded/pending).

In [190]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 5000

transactions = pd.DataFrame({
    "transaction_id": np.arange(1, n + 1),
    "customer_id": np.random.randint(1, 501, n),
    "product_id": np.random.randint(1, 201, n),
    "amount": np.round(np.random.uniform(5, 500, n), 2),
    "payment_method": np.random.choice(
        ["credit_card", "paypal", "bank_transfer", "cash"], n
    ),
    "timestamp": pd.date_range("2024-01-01", periods=n, freq="h"),
    "status": np.random.choice(
        ["completed", "refunded", "pending"], n, p=[0.8, 0.1, 0.1]
    )
})

transactions.head()

,transaction_id,customer_id,product_id,amount,payment_method,timestamp,status
0,1,103,136,286.90,cash,2024-01-01 00:00:00,completed
1,2,436,120,417.03,credit_card,2024-01-01 01:00:00,completed
2,3,349,126,495.85,paypal,2024-01-01 02:00:00,completed
3,4,271,55,85.99,cash,2024-01-01 03:00:00,completed
4,5,107,27,347.43,cash,2024-01-01 04:00:00,completed

In [191]:
transactions.tail()

,transaction_id,customer_id,product_id,amount,payment_method,timestamp,status
4995,4996,111,90,389.20,cash,2024-07-27 03:00:00,completed
4996,4997,415,85,245.77,bank_transfer,2024-07-27 04:00:00,completed
4997,4998,290,17,116.25,credit_card,2024-07-27 05:00:00,completed
4998,4999,295,80,101.61,credit_card,2024-07-27 06:00:00,completed
4999,5000,451,188,86.87,credit_card,2024-07-27 07:00:00,completed

## Step 2: Simulate OLTP-style operations:

Look up a single transaction by its ID (simulate a point query).
Insert a new transaction (append a row).
Update the status of a transaction from "pending" to "completed."
Check that the transaction is valid: the amount must be positive and the status must be one of the allowed values (simulate a consistency check)

In [192]:
transactions.loc[transactions['transaction_id']== 47, :]

,transaction_id,customer_id,product_id,amount,payment_method,timestamp,status
46,47,190,12,410.74,bank_transfer,2024-01-02 22:00:00,completed

In [193]:
transactions = pd.concat([
    transactions,
    pd.DataFrame([{
        "transaction_id": 5001,
        "customer_id": 233,
        "product_id": 122,
        "amount": 356.23,
        "payment_method": "paypal",
        "timestamp": "2024-07-27 08:00:00",
        "status": "pending"
    }])
], ignore_index=True)

In [194]:
transactions.tail()

,transaction_id,customer_id,product_id,amount,payment_method,timestamp,status
4996,4997,415,85,245.77,bank_transfer,2024-07-27 04:00:00,completed
4997,4998,290,17,116.25,credit_card,2024-07-27 05:00:00,completed
4998,4999,295,80,101.61,credit_card,2024-07-27 06:00:00,completed
4999,5000,451,188,86.87,credit_card,2024-07-27 07:00:00,completed
5000,5001,233,122,356.23,paypal,2024-07-27 08:00:00,pending

In [195]:
transactions.loc[transactions['transaction_id']== 5001, 'status'] = 'completed'

transactions.tail()

,transaction_id,customer_id,product_id,amount,payment_method,timestamp,status
4996,4997,415,85,245.77,bank_transfer,2024-07-27 04:00:00,completed
4997,4998,290,17,116.25,credit_card,2024-07-27 05:00:00,completed
4998,4999,295,80,101.61,credit_card,2024-07-27 06:00:00,completed
4999,5000,451,188,86.87,credit_card,2024-07-27 07:00:00,completed
5000,5001,233,122,356.23,paypal,2024-07-27 08:00:00,completed

In [196]:
((transactions['amount']).all() > 0 and transactions['status'].isin(["completed", "refunded", "pending"]).all())

np.True_

## Step 3: Simulate OLAP-style operations on the same data:

Compute total revenue by payment method.
Find the average transaction amount by month.
Identify the top 10 customers by total spending.
Compute the refund rate (percentage of refunded transactions).

In [197]:
total_revenue_by_payment = transactions.groupby('payment_method')['amount'].sum()
total_revenue_by_payment

payment_method
bank_transfer    313716.12
cash             304911.62
credit_card      308742.75
paypal           320160.41
Name: amount, dtype: float64

In [198]:
transactions['timestamp'] = pd.to_datetime(transactions['timestamp'])

In [199]:
avg_transaction_by_month = transactions.groupby(transactions['timestamp'].dt.month)['amount'].mean()
avg_transaction_by_month

timestamp
1    253.459677
2    249.116724
3    241.203629
4    249.527819
5    249.852218
6    247.200375
7    256.843302
Name: amount, dtype: float64

In [200]:
transactions.groupby('customer_id')['amount'].sum().sort_values(ascending= False).head(10)

customer_id
227    5746.71
173    5719.68
147    5396.70
154    5135.62
113    5104.17
152    5029.76
12     4959.40
192    4923.60
42     4905.91
376    4903.81
Name: amount, dtype: float64

In [201]:
percentage_refunded_transactions = f"{len(transactions[transactions['status']== 'refunded'])/ len(transactions)*100 : .2f} %"
print( percentage_refunded_transactions)

 10.28 %

## Step 4: Write a markdown cell explaining: 
Why would OLTP operations typically use row-major storage while OLAP operations use column-major storage? How does the access pattern of each workload type map to the memory layout that serves it best?

### Why OLTP uses row-major storage and OLAP uses column-major storage

OLTP (Online Transaction Processing) systems are designed for fast, frequent operations on individual records, such as inserting a transaction, updating a status, or retrieving a single row by its ID. These operations usually access **all attributes of one specific row** at once. In a **row-major storage layout**, all the columns of a row are stored together in memory. This means that when a single transaction record is accessed, the database can read the entire row efficiently in one contiguous block of memory. This layout minimizes disk and memory access for point queries and updates, which are common in OLTP workloads.

OLAP (Online Analytical Processing) systems, on the other hand, are optimized for analytical queries over large datasets. These queries typically perform **aggregations on specific columns**, such as calculating totals, averages, or counts across millions of records. In a **column-major storage layout**, values from the same column are stored together in contiguous memory. This allows the system to scan only the relevant columns needed for the calculation instead of reading every column in each row. As a result, column-major storage significantly improves performance for operations like grouping, filtering, and aggregating large datasets.

In summary, the choice of storage layout matches the **access pattern of the workload**. OLTP workloads access and modify **complete rows**, so row-major storage is more efficient. OLAP workloads analyze **specific columns across many rows**, so column-major storage enables faster scanning and more efficient analytical processing.

# Task 5: Choosing the Right Model
For each of the following real-world scenarios, recommend a data model (relational, document, or graph) and a processing paradigm (OLTP or OLAP). Write 3-4 sentences justifying each choice.

**A hospital patient record system where doctors need to quickly look up a patient's complete medical history.**

**Recommended data model:** Relational  
**Processing paradigm:** OLTP  

A hospital patient record system must handle structured data such as patient demographics, diagnoses, medications, and visit records, which fit naturally into a relational schema with well-defined relationships between tables. Relational databases provide strong consistency and support transactions, which are essential for maintaining accurate medical records. Doctors typically need to quickly retrieve or update a single patient's information, which is characteristic of OLTP workloads. Because these operations involve frequent inserts, updates, and point lookups rather than large-scale analysis, an OLTP system is the most appropriate choice.

**A social network that needs to suggest "friends of friends" connections.**

 **Recommended data model:** Graph  
**Processing paradigm:** OLTP  

A social network stores many relationships between users, such as friendships, follows, and interactions. The graph data model represents these connections naturally as nodes (users) and edges (friend relationships). Queries like “friends of friends” require traversing multiple connections, which graph databases handle efficiently through relationship traversal. These operations are typically real-time lookups and updates on user connections, making them characteristic of OLTP workloads.

**A financial reporting system that computes monthly revenue breakdowns across product categories and regions.**

**Recommended data model:** Relational (column-oriented warehouse)  
**Processing paradigm:** OLAP  

A financial reporting system performs analytical queries that aggregate large volumes of transaction data to compute metrics such as monthly revenue by product category and region. These workloads involve scanning many records and performing operations like grouping, filtering, and summing values across columns. Relational data warehouses with column-oriented storage are well suited for this type of analytical processing because they allow efficient column scans and aggregations. Since the focus is on reporting and analysis rather than frequent transactional updates, an OLAP processing paradigm is the most appropriate choice.

**An IoT platform that receives sensor readings from 10,000 devices and needs to detect anomalies in real time.**

**Recommended data model:** Document  
**Processing paradigm:** OLTP  

An IoT platform receives continuous streams of sensor readings from thousands of devices, where each reading can naturally be represented as a document containing fields such as device_id, timestamp, and sensor values. The document model is flexible and works well with semi-structured data, allowing different devices to send slightly different data formats without requiring schema changes. The system must process incoming readings quickly and detect anomalies as soon as they arrive, which requires fast inserts and real-time queries. Because the workload involves high-frequency writes and immediate checks on individual records, it fits the characteristics of an OLTP processing paradigm.

**A content management system where each article has a different set of metadata fields.**

**Recommended data model:** Document  
**Processing paradigm:** OLTP  

A content management system often stores articles that may have different metadata fields such as author, tags, category, publication date, or custom attributes. Because the structure of this metadata can vary between articles, a document data model is well suited since it allows flexible and semi-structured data without requiring a fixed schema. Each article can be stored as a document with its own set of fields. The system mainly performs frequent operations such as creating, updating, and retrieving individual articles, which aligns with the characteristics of OLTP workloads.